spring.datasource.url=jdbc:postgresql://localhost:5432/wageclock
spring.datasource.username=wageclock
spring.datasource.password=wageclock
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret=wageclock-secret-key-must-be-at-least-256-bits-long
portone.api-secret=z1Fh7hvxCPZld3KiFC9MTC7Q8GYW4qciqZa1MrodhKv2pd1HYOdNAtgNvI1cj2dPKosTpVMh37sdv20x
portone.store-id=store-6da5ea12-0a97-426a-a8b5-4df76b3db702
portone.channel-key=channel-key-88744ae9-f7d0-413a-8959-2aec728afd14