spring.application.name=wageclock

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wageclock
spring.datasource.username=wageclock
spring.datasource.password=wageclock
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#port
server.port=8081